package com.gof.ark.entity;

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.gof.entity.MstCalc;
import com.gof.enums.EOperator;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
* MstBoxCoa generated by hbm2java
*/
@Entity
@IdClass(ArkBoxMapId.class)
@Table(name = "ARK_BOX_MAP")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
//@Slf4j
public class ArkBoxMap implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

//	@Id private String calcId;
	@ManyToOne
	@JoinColumn(name = "CALC_ID")
	@Id private MstCalc mstCalc;
	
	
	@ManyToOne
	@JoinColumn(name = "ARK_RUNSET_ID")
	@Id private ArkMstRunset arkMstRunset;
	
//	@Id private String runsetId;
	@Id private String itemId;
	
	@Enumerated(EnumType.STRING)
	private EOperator signAdjust;
	
	private String remark;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	public String getMapKey() {
		return arkMstRunset.getArkRunsetId()+ itemId;
	}
}
