package com.gof.ark.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.gof.enums.ECfType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * CfLv1Raw generated by hbm2java
 */
@Entity
@IdClass(ArkRawEpvDetailId.class)
@Table(name = "RAW_GOC_ARK_EPV_DETAIL")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ArkRawEpvDetail implements Serializable {
	private static final long serialVersionUID = -8151467682976876533L;
	
	@Id	private String driveYm;
	@Id	private String setlYm;
	@Id	private String exeIdno;
	@Id	private String rsDivId;
	@Id	private String csmGrpCd;
	@Id	private String bemmStcd;
	@Id	private String emmStcd;
	@Id	private String ctrDvcd;
	
	@Enumerated(EnumType.STRING)
	@Id	private ECfType cfType;
	
	private Double cfAmt;	
	
	private Double epvAmt;
	
//	@Column(name = "MM1_AF_BEL_AMT")
//	private Double mm1AfBelAmt;
//	
//	@Column(name = "MM2_AF_BEL_AMT")
//	private Double mm2AfBelAmt;
//	
//	@Column(name = "MM3_AF_BEL_AMT")
//	private Double mm3AfBelAmt;
	

	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	@Override
	public String toString() {
		StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(setlYm).append(",")
	 		.append(exeIdno).append(",")
	 	 	.append(rsDivId).append(",")
	 	 	.append(csmGrpCd).append(",")
	 	 	.append(bemmStcd).append(",")
	 	 	.append(emmStcd).append(",")
	 	 	.append(ctrDvcd).append(",")
	 	 	.append(cfType).append(",")
	 	 	.toString();
	}
	
	public ArkRawEpvDetail(String setlYm, String rsDivId, String csmGrpCd, String bemmStcd, String emmStcd,String ctrDvcd, ECfType cfType, Double cfAmt, Double epvAmt) {
		this.setlYm = setlYm;
		this.rsDivId = rsDivId;
		this.csmGrpCd = csmGrpCd;
		this.bemmStcd = bemmStcd;
		this.emmStcd = emmStcd;
		this.ctrDvcd = ctrDvcd;
		this.cfType = cfType;
		this.cfAmt = cfAmt;
		this.epvAmt = epvAmt;
	}
}
