package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.gof.enums.EBoolean;
import com.gof.enums.ECfType;
import com.gof.enums.EContStatus;
import com.gof.enums.ELiabType;
import com.gof.enums.ETiming;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * CfLv3Real generated by hbm2java
 */
@Entity
@Table(name = "CF_LV3_REAL")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CfLv3Real implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;
	
	@Id
	@SequenceGenerator(name = "CF_LV3_SEQ", sequenceName = "CF_LV3_SEQ", initialValue = 1, allocationSize = 50)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CF_LV3_SEQ" )
	private Long seqId;
	
	private String baseYymm;
	private String gocId;
	
	private String runsetId;
	
	@Enumerated(EnumType.STRING)
	private ELiabType liabType;
	
	@Enumerated(EnumType.STRING)
	@Id private EContStatus stStatus;
	
	@Enumerated(EnumType.STRING)
	@Id private EContStatus endStatus;
	
	
	@Enumerated(EnumType.STRING)
	private EBoolean newContYn;
	
	private String cfKeyId;
	
	@Enumerated(EnumType.STRING)
	private ECfType cfType;
	
	@Enumerated(EnumType.STRING)
	private EBoolean outflowYn;
	
	private String cfStartYymm;
	private String cfEndYymm;
	
	private Double cfAmt;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	public ETiming getCfTiming() {
		return ETiming.END;
	}

	public Double getCfMonthNum() {
		return 0.0;
	}
	
	public boolean isFutureCf(double forwardingNum) {
		return false;
	}
	
	
	@Override
	public String toString() {
		 StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(baseYymm).append(",")
	 	 	.append(gocId).append(",")
	 	 	.append(runsetId).append(",")
	 	 	.append(liabType).append(",")
	 	 	.append(stStatus).append(",")
	 	 	.append(endStatus).append(",")
	 	 	.append(newContYn).append(",")
	 	 	.append(cfType).append(",")
	 	 	.append(cfAmt).append(",")
	 	 	.toString();
	}
	
	public CfLv3Real(String baseYymm, String gocId, String runsetId, ELiabType liabType, EContStatus stStatus, EContStatus endStatus, EBoolean newContYn, ECfType cfType, Double cfAmt) {
		this.baseYymm = baseYymm;
		this.gocId = gocId;
		this.runsetId = runsetId;
		this.liabType = liabType;
		this.stStatus = stStatus;
		this.endStatus = endStatus;
		this.newContYn = newContYn;
		this.cfType = cfType;
		this.cfAmt = cfAmt;
	}
	
}
