package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.gof.enums.ELiabType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * RstEir generated by hbm2java
 */
@Entity
@IdClass(DfLv4EirId.class)
@Table(name = "DF_LV4_EIR")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DfLv4Eir implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id private String baseYymm;
	@Id private String gocId;
	
	@Id
	@Enumerated(EnumType.STRING)
	private ELiabType liabType;
	
	private String eirAplyRunset;
	private Double eir;
	private Double epvAmt;
	
	private Double targetOci;
	private Double errorAmt;
	
	private String remark;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	@Override
	public String toString() {
		 StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(baseYymm).append(",")
	 	 	.append(gocId).append(",")
	 	 	.append(liabType).append(",")
	 	 	.append(eir).append(",")
	 	 	.append(epvAmt).append(",")
	 	 	.append(targetOci).append(",")
	 	 	.append(remark).append(",")
	 	 	.toString(); 
	}
}
