package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Embeddable;

import lombok.Getter;

/**
 * MapCfGroupId generated by hbm2java
 */
@Embeddable
@Getter
public class MapJournalRollFwdId implements java.io.Serializable {
	
	private static final long serialVersionUID = -8151467682976876533L;
	
//	@Enumerated(EnumType.STRING)
//	private ERollFwdType rollFwdType;
	
	private MstRollFwd mstRollFwd;
	
//	@Id	private String calcId;
//	private MstCalc calcId;
//	@ManyToOne
//	@JoinColumn(name = "CALC_ID")
	private MstCalc mstCalc;
	
	private int subSeq;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	

}
