package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

import com.gof.enums.EProfitDiv;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * MstContGoc generated by hbm2java
 */
@Entity
@Table(name = "MST_CONT_GOC")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MstContGoc implements java.io.Serializable {
private static final long serialVersionUID = -8151467682976876533L;
	
	@Id	private String ctrPolno;
	private String prodCd;
	
	private String ctrDt;
	private String initYymm;
	
	private String cohort;
	private String portCd;
	private String csmGroupCd;
	private String raGroupId;
	
	@Enumerated(EnumType.STRING)
	private EProfitDiv profitCd;
	
	private String gocId;
	private String changedGocId;

	private String remark;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
//	@Override
//	public String getBaseYymm() {
//		return null;
//	}
}
