package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

import com.gof.enums.EBoolean;
import com.gof.enums.ECalcType;
import com.gof.enums.ECoa;
import com.gof.enums.EOperator;
import com.gof.enums.ERollFwdType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * MstRollFwd generated by hbm2java
 */
@Entity
@Table(name = "MST_CALC_RFWD_DETAIL")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MstCalcRfwdDetail implements Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id private String calcId;			
	
	private int seq;
	
	@Enumerated(EnumType.STRING)
	private ECalcType calcSubType;

	
	@Enumerated(EnumType.STRING)
	private ECoa coaId;
	
	@Enumerated(EnumType.STRING)
	private ERollFwdType refRollFwdType;
	
	@Enumerated(EnumType.STRING)
	private EBoolean ratioAdjustYn;

	private String ratioId;
	
	@Enumerated(EnumType.STRING)
	private EOperator signAdjust;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	@Override
	public String  toString() {
		return calcId;
	}
}
