package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

import com.gof.enums.EBoolean;
import com.gof.enums.EConvType;
import com.gof.enums.EGocDiv;
import com.gof.util.DateUtil;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * MstGoc generated by hbm2java
 */
@Entity
@Table(name = "MST_GOC")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MstGoc implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;
	
	@Id private String gocId;
	private String gocNm;
	private String gocGroup;
	private String portCd;
	private String portNm;
	private String csmGroupCd;
	private String cohort;
	private String initYymm;
	private String profitCd;
	private String raGroupId;
	
	
	@Enumerated(EnumType.STRING)
	private EConvType convType;
	
	@Enumerated(EnumType.STRING)
	private EBoolean ociYn;
	
	@Enumerated(EnumType.STRING)
	private EBoolean eirYn;
	
	private String covUnitDiv;
	
	@Enumerated(EnumType.STRING)
	private EBoolean useYn;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	
	public String getInitCurveYymm() {
		return convType.isAfterTransYn()? DateUtil.addMonthToString(initYymm, -1): initYymm;
//		return DateUtil.addMonthToString(initYymm, -1);
	}
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	@Override
	public String toString() {
		return gocId;
	}
	
	public MstGoc updateUseYn() {
		this.useYn =EBoolean.Y;
		return this;
	}
	public EGocDiv getGocDiv(String stBssd, String bssd) {
		if(DateUtil.isGreaterThan(initYymm, stBssd)  && DateUtil.isGreaterOrEqual(bssd, initYymm)) {
			return EGocDiv.NEW;
		}
		return EGocDiv.HOLDING;
	}
}