package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

import com.gof.dao.DfDao;
import com.gof.enums.EBoolean;
import com.gof.util.DateUtil;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * MstGoc generated by hbm2java
 */
@Entity
@Table(name = "MST_RS_DIV")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MstRsDiv implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;
	
	@Id private String rsDivId;
	
	@Enumerated(EnumType.STRING)
	private EBoolean prevCurveYn;
	
		
	private String rsType;
	private String remark;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	public List<DfLv1CurrRate> getCurveList(String bssd, String irCurveId){
		String curveYymm  = prevCurveYn.isTrueFalse()?DateUtil.addMonthToString(bssd, -1): bssd;
		return  DfDao.getDfLv1CurrRate(curveYymm, irCurveId);
	}
}