package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.gof.interfaces.INcontRst;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * NewcontRstEpv generated by hbm2java
 */
@Entity
@IdClass(NcontRstEpvId.class)
@Table(name = "NCONT_RST_EPV")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NcontRstEpv implements java.io.Serializable, INcontRst {
private static final long serialVersionUID = -8151467682976876533L;
	
	@Id private String baseYymm;
	@Id private String ctrPolno;
	@Id private String prodCd;

	private Double outCfAmt;
	private Double inCfAmt;
	private Double cfAmt;
	private Double outEpvAmt;
	private Double inEpvAmt;
	private Double epvAmt;
	private String remark;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	public String getPk() {
		StringBuilder builder = new StringBuilder();
		return builder.append(ctrPolno).append(",")
					  .append(prodCd).append(",")
					  .toString();
	}
	
//	public NcontRstEpv(String baseYymm, String ctrPolno, String stStatus, String endStatus, String newContYn,EBoolean outflowYn, String prodCd, Double cfAmt, Double epvAmt) {
//		this.baseYymm = baseYymm;
//		this.ctrPolno = ctrPolno;
//		this.prodCd = prodCd;
//		this.cfAmt = cfAmt;
//		this.epvAmt = epvAmt;
//	}
	
	public NcontRstEpv  merge(NcontRstEpv other) {
		double cfAmt = this.getCfAmt(); 
		double epvAmt  = this.getEpvAmt();
		double otherCfAmt  =other.getCfAmt();
		double otherEpvAmt =other.getEpvAmt();
		
		 return NcontRstEpv.builder()
				 			.baseYymm(baseYymm)
				 			.ctrPolno(ctrPolno)
				 			.prodCd(prodCd)
				 			.cfAmt(cfAmt 	+ otherCfAmt)
				 			.epvAmt(epvAmt	+ otherEpvAmt)
				 			.build();
		
	}
	public NcontRstEpv(String baseYymm, String ctrPolno, String prodCd, Double cfAmt, Double epvAmt) {
		this.baseYymm = baseYymm;
		this.ctrPolno = ctrPolno;
		this.prodCd = prodCd;
		this.cfAmt = cfAmt;
		this.epvAmt = epvAmt;
	}
}
