package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * RstRa generated by hbm2java
 */
@Entity
@IdClass(RawRatioLossRcvId.class)
@Table(name = "RAW_RATIO_LOSS_RCV")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RawRatioLossRcv implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id private String setlYm;
	@Id private String lossRcvStep;
	@Id private String ulGocId;
	@Id private String gocId;
	
	
	private double numerator;
	private double denominator; 
	private double ratio;
	
	private String ulRsDivId;
	private String rsDivId;
	
//	private String remark;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	public String getPk() {
		return ulGocId+lossRcvStep;
	}
}
