package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.gof.enums.ETiming;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * RstRa generated by hbm2java
 */
@Entity
@IdClass(RawRaIbnrId.class)
@Table(name = "RAW_GOC_RA_IBNR")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RawRaIbnr implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id private String driveYm;
	@Id private String setlYm;
	@Id private String rsDivId;
	@Id private String csmGrpCd;
	@Id private String bemmStcd;
	@Id private String emmStcd;
	@Id private String ctrDvcd;
	@Id private int setlAftPassMmcnt;
	
	@Enumerated(EnumType.STRING)
	private ETiming cfTiming;
	private double raAmt;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}
