package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * RstTvog generated by hbm2java
 */

@Entity
@IdClass(RawTvogId.class)
@Table(name = "RAW_CONT_TVOG")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RawTvog implements java.io.Serializable{
	private static final long serialVersionUID = -8151467682976876533L;

	@Id private String baseYymm;
	@Id private String ctrPolno;
	@Id private String prmctrSicSrno;
	@Id private String rsDivId;

	private String prodCd;
	private String prmctrProdCd;
	private Double tvogAmt;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}