package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.gof.enums.ELiabType;
import com.gof.infra.GmvConstant;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * RstRa generated by hbm2java
 */
@Entity
@IdClass(RstLossRcvId.class)
@Table(name = "RST_LOSS_RCV_DETAIL")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RstLossRcv implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id private String baseYymm;
	@Id private String gocId;
	@Id private String ulGocId;
	
	@Enumerated(EnumType.STRING)
	@Id private ELiabType liabType;
	
	@ManyToOne
	@JoinColumn(name = "RUNSET_ID")
	@Id	private MstRunset mstRunset;
	
//	@Id private String runsetId;
	
	@Id private String calcId;
	@Id private String ulCalcId;
	@Id private String stStatus;
	@Id private String endStatus;
	@Id private String newContYn;
	
		
	private Double lossAdjAmt; 
	private Double boxValue; 

	private String lossRcvStep;
	private Double ratio;  			 
	private Double numerator;  		
	private Double denominator;  	

	private String remark;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
	 	 return builder
	 	 	.append(baseYymm).append(",")
	 	 	.append(gocId).append(",")
	 	 	.append(ulGocId).append(",")
	 	 	.append(liabType).append(",")
	 	 	.append(stStatus).append(",")
	 	 	.append(endStatus).append(",")
	 	 	.append(newContYn).append(",")
	 	 	.toString();
	}
	
	public RstLossRcv(String baseYymm, String gocId, ELiabType liabType, MstRunset mstRunset, String calcId, String stStatus,
			String endStatus, String newContYn, Double lossAdjAmt, Double boxValue) {
		this.baseYymm = baseYymm;
		this.gocId = gocId;
		this.liabType = liabType;
		this.mstRunset = mstRunset;
		this.calcId = calcId;
		this.stStatus = stStatus;
		this.endStatus = endStatus;
		this.newContYn = newContYn;
		this.lossAdjAmt = lossAdjAmt;
		this.boxValue = boxValue;
		this.lastModifiedBy =GmvConstant.getLastModifier();
		this.lastModifiedDate = LocalDateTime.now();
	}
	

	
}
