package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.gof.enums.EBoolean;
import com.gof.enums.EBoxModel;
import com.gof.enums.ECfType;
import com.gof.enums.ECoa;
import com.gof.enums.ELiabType;
import com.gof.enums.ETiming;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * AcctBox generated by hbm2java
 */
@Entity
@IdClass(AcctBoxId.class)
@Table(name = "ACCT_BOX")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class AcctBox implements Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id private String baseYymm;
	@Id private String gocId;
	
	@Enumerated(EnumType.STRING)
	@Id private ELiabType liabType;
	
	@Id private String stStatus;
	@Id private String endStatus;
	
	@Enumerated(EnumType.STRING)
	@Id private EBoolean newContYn;
	@Id private String cfKeyId;
	
	private Integer cfColSeq;
	private String cfId;
	
	@Enumerated(EnumType.STRING)
	private ECfType cfType;

	@Enumerated(EnumType.STRING)
	@Id private ETiming cfTiming;
	
	@Enumerated(EnumType.STRING)
	@Id private EBoolean outflowYn;
	
	@Id private Double cfMonthNum;
	
	
	@Id private String runsetId;
	@Id private String journalId;
	@Id	private String rollFwdType;
	
	private Integer rollFwdSeq;
	
//	@Id
	@Enumerated(EnumType.STRING)
	private EBoxModel boxId;
	
	@Enumerated(EnumType.STRING)
	private ECoa debtCoa;
	
	@Enumerated(EnumType.STRING)
	private ECoa creditCoa;

	private Double cfAmt;
	private Double prevCfAmt;
	private Double deltaCfAmt;
	private Double boxAmt;
	private Double coaAmt;
	private String remark;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	public double getSignCoaAmt(ECoa coa) {
		if(coa.equals(debtCoa)){ 
			return coaAmt * -1 * coa.getSign();
		}else {
			return coaAmt * coa.getSign();
		}
	}
	
	public boolean isRelateTo(ECoa coa) {
		return coa.equals(debtCoa) || coa.equals(creditCoa);
	}
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	@Override
	public String toString() {
		 StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(baseYymm).append(",")
	 	 	.append(gocId).append(",")
	 	 	.append(stStatus).append(",")
	 	 	.append(endStatus).append(",")
	 	 	.append(newContYn).append(",")
	 	 	.append(cfKeyId).append(",")
	 	 	.append(cfTiming).append(",")
	 	 	.append(outflowYn).append(",")
	 	 	.append(cfMonthNum).append(",")
	 	 	.append(runsetId).append(",")
	 	 	.append(journalId).append(",")
	 	 	.append(rollFwdType).append(",")
	 	 	.append(boxAmt).append(",")
	 	 	.append(coaAmt).append(",")
	 	 	.toString();
	}
}
