package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.gof.enums.EBoolean;
import com.gof.enums.EContStatus;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * RstEirNewgoc generated by hbm2java
 */
@Entity
@IdClass(DfLv2EirNewgocId.class)
@Table(name = "DF_LV2_EIR_NEWGOC")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DfLv2EirNewgoc implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id	private String baseYymm;
	@Id	private String gocId;
	
	@Enumerated(EnumType.STRING)
	@Id	private EContStatus stStatus;			//TODO : new cont 는 모두 "01"???
	
	@Enumerated(EnumType.STRING)
	@Id	private EContStatus endStatus;			//TODO : new cont 는 모두 "01"???
	
	@Enumerated(EnumType.STRING)
	@Id	private EBoolean newContYn;
	
	
	private Double eir;
	private Double fincEpvAmt;
	private Double targetRunSysAmt;
	
	private Double targetRunOci;
	private Double deltaOci;
	private Double fincOci;
	private Double targetOci;
	
	private Double errorAmt;
	private String remark;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	
	public String getPkForEir() {
		 StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(baseYymm).append(",")
	 	 	.append(gocId).append(",")
	 	 	.append(stStatus).append(",")
	 	 	.append(endStatus).append(",")
//	 	 	.append(newContYn).append(",")
	 	 	.toString(); 
	}
	
	@Override
	public String toString() {
		 StringBuilder 	builder = new StringBuilder();
	 	 return builder
	 		.append(baseYymm).append(",")
	 	 	.append(gocId).append(",")
	 	 	.append(stStatus).append(",")
	 	 	.append(endStatus).append(",")
	 	 	.append(newContYn).append(",")
	 	 	.append(eir).append(",")
	 	 	.append(fincEpvAmt).append(",")
	 	 	.append(targetRunSysAmt).append(",")
	 	 	.append(targetOci).append(",")
	 	 	.append(remark).append(",")
	 	 	.toString(); 
	}
}
