package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;

import com.gof.enums.EBoolean;
import com.gof.enums.EContStatus;

import lombok.Getter;

/**
 * RstEirNewgocId generated by hbm2java
 */
@Embeddable
@Getter
public class DfLv2EirNewgocId implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	private String baseYymm;
	private String gocId;
	
	@Enumerated(EnumType.STRING)
	@Id	private EContStatus stStatus;			//TODO : new cont 는 모두 "01"???
	
	@Enumerated(EnumType.STRING)
	@Id	private EContStatus endStatus;	
	
	@Enumerated(EnumType.STRING)
	private EBoolean newContYn;
		
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}
