package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

import com.gof.enums.ECfType;

import lombok.Getter;

/**
 * MapCfGroupId generated by hbm2java
 */
@Embeddable
@Getter
public class MapCfGroupId implements java.io.Serializable {
	
	private static final long serialVersionUID = -8151467682976876533L;
	
//	private String cfGroupId;
	private MstCfGroup cfGroup;
	
//	@Enumerated(EnumType.STRING)
//	private ECfType cfType;
	private String cfKeyId;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	

}
