package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import static java.util.stream.Collectors.toList;

import java.time.LocalDateTime;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.gof.enums.ECfType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * MstCfBnf generated by hbm2java
 */
@Entity
@Table(name = "MST_CF_CLASS")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MstCfClass implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id	private String cfClassId;
	private String cfClassName;
	private String remark;
	private String useYn;
	
	@OneToMany(mappedBy = "cfClass", fetch = FetchType.EAGER)
	private List<MapCfClass> cfClassList;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	
	
	public List<ECfType> getCfTypeList(){
		return cfClassList.stream().map(s->s.getCfType()).collect(toList());
	}
	
	public boolean contatins(ECfType cfType) {
		return getCfTypeList().contains(cfType);
	}
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}
