package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * MstCfBnf generated by hbm2java
 */
@Entity
@IdClass(MstCfBnfId.class)
@Table(name = "MST_CF_BNF")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MstCfBnf implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id	private String prodCd;
	@Id	private String cfProdCd;
	
	@Id	private String bnftSrno;
	@Id	private String bnftCd;
	
	private String bnftNm;
	
	private String cfId;
	private String cfIdNm;
	
	private String cfEstYn;
	private String cfGroup;
	
	private String cfGroupNm;
	private String cfType;
	private String cfTiming;
	private String outflowYn;
	private String useYn;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}
