package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import com.gof.interfaces.INcontRst;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * NewcontRstRa generated by hbm2java
 */
@Entity
@IdClass(NcontRstRaId.class)
@Table(name = "NCONT_RST_RA")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class NcontRstRa implements java.io.Serializable, INcontRst {
private static final long serialVersionUID = -8151467682976876533L;
	
	@Id private String baseYymm;
	@Id private String ctrPolno;
	@Id private String prodCd;
	
	private String raCalcType;
	private Double raRatio;
	private Double raAmt;
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;

	public NcontRstRa(String baseYymm, String ctrPolno, Double raAmt) {
		this.baseYymm = baseYymm;
		this.ctrPolno = ctrPolno;
		this.raAmt = raAmt;
	}
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
}
