package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

import com.gof.enums.ECoa;

import lombok.Getter;

/**
 * RstDacId generated by hbm2java
 */
@Embeddable
@Getter
public class RstDacId implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	private String baseYymm;
	private String gocId;
	
	@Enumerated(EnumType.STRING)
	private ECoa coaId;
	
//	@Enumerated(EnumType.STRING)
//	private ERollFwdType rollFwdType;
	private MstRollFwd mstRollFwd;
	
//	
//	private String runsetId;
//	private String calcId;
	
	private String runsetId;
	private MstCalc mstCalc;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
}
