package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.gof.enums.ECoa;
import com.gof.enums.EOperator;
import com.gof.enums.ERollFwdType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * RstRollFwd generated by hbm2java
 */
@Entity
@IdClass(RstRollFwdId.class)
@Table(name = "RST_ROLL_FWD_LOSS")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder

public class RstRollFwdLoss implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

	@Id	private String baseYymm;
	@Id	private String gocId;
	
	@Enumerated(EnumType.STRING)
	@Id	private ECoa coaId;
	
	@Id	private String 	runsetId;				//TODO Enum change
//	@Id	private String 	calcId;					//TODO Enum change
	
	@ManyToOne
	@JoinColumn(name = "CALC_ID")
	@Id	private MstCalc	mstCalc;					//TODO Enum change

	@Enumerated(EnumType.STRING)
	@Id	private ERollFwdType	rollFwdType;				//TODO Enum change
	
	private int rollFwdSeq;
	private int runsetSeq;
	
	@Enumerated(EnumType.STRING)
	private EOperator operatorType;
	
	private Double boxAmt;
	private Double deltaAmt;
	private Double closeAmt;
	
//	private Double deltaLossAmt;
//	private Double closeLossAmt;
//	private Double rollFwdAmt;
	private String remark;
	
	private String lastModifiedBy;
	private LocalDateTime lastModifiedDate;
	
	public double getAppliedAmt() {
		return rollFwdType.isClose() ? closeAmt: deltaAmt;
	}
	
	public String getPk() {
		return rollFwdType+getCalcId();
	}
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		 return builder
			 	 	.append(baseYymm).append(",")
			 	 	.append(gocId).append(",")
			 	 	.append(coaId).append(",")
			 	 	.append(rollFwdType).append(",")
			 	 	.append(runsetId).append(",")
			 	 	.append(mstCalc.getCalcId())
			 	 	.toString(); 
	}

	public String getCalcId() {
		return mstCalc.getCalcId();
	}
//	public String getPostingGroup() {
//		switch (coaId) {
//		case DAC: 	return ERollFwdDac.valueOf(rollFwdType).getPostGroup().name();
//		case RA:	return ERollFwdRa.valueOf(rollFwdType).getPostGroup().name();
//		case TVOG:	return ERollFwdTvog.valueOf(rollFwdType).getPostGroup().name();
//		case CSM:
//			break;
//		default:
//			break;
//		}
//		return "CURR_CLOSING";
//	}
	
}
