package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Embeddable;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.gof.enums.ECoa;
import com.gof.enums.ERollFwdType;

import lombok.Getter;

/**
 * RstRollFwdId generated by hbm2java
 */
@Embeddable
@Getter
public class RstRollFwdId implements java.io.Serializable {
	private static final long serialVersionUID = -8151467682976876533L;

		
	private String baseYymm;
	private String gocId;
	
	@Enumerated(EnumType.STRING)
	private ECoa coaId;
	
			
	private String 	runsetId;				//TODO Enum change
//	private String 	calcId;
	
	@ManyToOne
	@JoinColumn(name = "CALC_ID")
	private MstCalc	mstCalc;					//TODO Enum change
	
//	private ERollFwdDac rollFwdType;
	@Enumerated(EnumType.STRING)
	private ERollFwdType rollFwdType;
	
	
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		 return builder
			 	 	.append(baseYymm).append(",")
			 	 	.append(gocId).append(",")
			 	 	.append(coaId).append(",")
			 	 	.append(rollFwdType).append(",")
			 	 	.append(runsetId).append(",")
			 	 	.append(mstCalc.getCalcId())
			 	 	.toString(); 
	}
	
}
