package com.gof.entity;
// Generated 2020. 1. 16 ���� 3:15:14 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * CfLv2Goc generated by hbm2java
 */
@Entity
@Table(name = "TST_SEQ")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
//@Slf4j
public class TstSeq implements java.io.Serializable{
	private static final long serialVersionUID = -8151467682976876533L;
	
	@Id
	@SequenceGenerator(name = "CF_SEQ_JPA", sequenceName = "CF_SEQ", initialValue = 1, allocationSize = 50)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CF_SEQ_JPA")
	private Long cfId;
	
	@Override
	public boolean equals(Object arg0) {
		return super.equals(arg0);
	}
	@Override
	public int hashCode() {
		return super.hashCode();
	}
	@Override
	public String toString() {
//		return String.valueOf(cfId);
		StringBuilder 	builder = new StringBuilder();
	 	return builder.append(cfId).toString();
	}
}
